spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookmanager?serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: bookmanager


server:
  port: 9999

mybatis-plus:
  #mp日志,输出到控制台
#    configuration:
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mp的banner的关闭
    global-config:
      banner: false
logging:
  level:
    root: warn